spring:
  data:
    mongodb:
      authentication-database: cd_pipeline_data
      username: coderw
      password: H5ye}X}5
      database: cd_pipeline_data
      port: 18001
      host: mongo-dev-rtp-pipeline-data


logging:
  level:
    org:
      springframework:
        data: debug
